### ISSUE TITLE
Church-encoded Maybe

### ISSUE THREAD

**Issue by ktonga** [scalaz/scalaz-io#3]
@jdegoes you in scalaz/scalaz#1798 specify that replacements for `Maybe` and `\/` should be church-encoded. Why exactly? as opposed to sum types.

So far I've got this, but dunno how to get rid of `B` type parameter, it should be using some sort of Haskell's `forall` but I can't figure out how to express that in Scala.

```scala
final class Perhaps[A, B] private (val perhaps: (B, A => B) => B) extends AnyVal {
  def map[C](g: A => C): Perhaps[C, B] = new Perhaps((b, f) => perhaps(b, f.compose(g)))
  def toOption: Option[A] = perhaps(None.asInstanceOf[B], a => Some(a).asInstanceOf[B]).asInstanceOf[Option[A]]
}

object Perhaps {
  def present[A, B](a: A): Perhaps[A, B] = new Perhaps((_, f) => f(a))
  def absent[A, B]: Perhaps[A, B] = new Perhaps((b, _) => b)
}
```

**Comment by jdegoes** [comment]
@ktonga Because it's something I wanted to do anyway, as it improves performance.

First off, internally, this repository can use the Scala standard library types (Option, List, etc.), which it already does for the most part.

Second, in the few places where a `Maybe` or `\/` is exposed, we can severe the dependency and improve performance in one go.

An example is `attempt`. Currently, it's typed as `def attempt[E2]: IO[E2, E \/ A]`. However, what's the first thing a user does when they attempt? Well, they either `map` or `flatMap`, fold / match against the `E \/ A`, and then convert it to something else. There's a more direct encoding:

```scala
def attempt[E2, B](err: E => IO[E2, B])(suc: A => IO[E2, B]): IO[E2, B]
```

Now, this form allocates two closures, but the the other form allocates a data structure and a closure, so you're equal at this point. Then if you do anything with the result, you come out ahead in the Church-encoded representation.

The resulting `IO` will not expose data structures in the API and will generally be faster. Then downstream libraries can choose data structures and add (via extension methods) appropriate helper functions specialized for different use cases.

**Comment by ktonga** [comment]
Oh right, church encoding in the API, not defining replacement data types. Gotcha. Will try that way then.

Thanks!

**Comment by jdegoes** [comment]
@ktonga This will be tricky in some places, lemme know if you need any help.

**Comment by ktonga** [comment]
@jdegoes how you like this encoding?

```scala
  final case class FromEA[E, A](err: E => IO[E, A], succ: A => IO[E, A])
  
  final def absolve[E, A, B](f: FromEA[E, A] => B => IO[E, A])(v: IO[E, B]): IO[E, A] =
    v.flatMap(f(FromEA[E, A](IO.fail, IO.now)))
```

**Comment by ktonga** [comment]
It enables internal/private shortcuts such as

```scala
  private def absolveEither[E, A](sinner: IO[E, Either[E, A]]) =
    IO.absolve[E, A, Either[E, A]](fea => b => b.fold(fea.err, fea.succ))(sinner)
```
And then

```scala
  final def syncCatch[E, A](effect: => A)(f: PartialFunction[Throwable, E]): IO[E, A] =
    IO.absolveEither[E, A](
      IO.sync(
        try {
          val result = effect
          Right(result)
        } catch {
          case t: Throwable if f.isDefinedAt(t) => Left(f(t))
        }
      )
    )
```

**Comment by ktonga** [comment]
And... without the useless intermediate `Either` allocation

```scala
  private def absolveF[E, A](sinner: IO[E, FromEA[E, A] => IO[E, A]]) =
    IO.absolve[E, A, FromEA[E, A] => IO[E, A]](fea => f => f(fea))(sinner)

  final def syncCatch[E, A](effect: => A)(f: PartialFunction[Throwable, E]): IO[E, A] =
    IO.absolveF[E, A](
      IO.sync(
        try {
          val result = effect
          _.succ(result)
        } catch {
          case t: Throwable if f.isDefinedAt(t) => _.err(f(t))
        }
      )
    )
```

**Comment by jdegoes** [comment]
@ktonga I would like to avoid any intermediate data structures, not just merely avoid `Either` / `Disjunction` / `Maybe`. Adding more parameters to a parameter list has no cost (by itself), but constructing and matching on data structures adds overhead. Also with your curried representation inside `FromEA`, it will add additional overhead.

For `attempt`, we really do need:

```scala
def attempt[E2, B](err: E => IO[E2, B])(suc: A => IO[E2, B]): IO[E2, B]
```

This is the fastest possible way to represent the same idea without data structures.

Now `absolve` is trickier because instead of the user needing to handle the disjunction, the library needs to handle the disjunction—the direction of arrows is flipped.

In the original definition:

```scala
final def absolve[E, A](v: IO[E, E \/ A]): IO[E, A]
```

To translate this one we need either rank-n types, which Scala does not have, or a trait that allows us to simulate it, which Scala does have:

```scala
trait Disjunction[A, B] {
  def fold[Z](left: A => Z, right: B => Z): Z
}

final def absolve[E, A, B](v: IO[E, A])(disj: A => Disjunction[E, B]): IO[E, B]
```

Now the `absolve` method has a proof that `A` is a disjunction between `E` and `B`, so it can perform the absolution. Possibly the order of parameters should be flipped:

```scala
final def absolve[E, A, B](disj: A => Disjunction[E, B])(v: IO[E, A]): IO[E, B]
```

This makes it easier for libraries (like Scalaz 8) to define helper methods (e.g. `absolveDisjunction`, `absolveEither`, etc.).

I think, but am not sure, that this is the only intermediate trait / data structure needed for any of the methods.

@ktonga What other examples are there? I would like to go through and ensure each one is translated as cleanly as possible with the minimal number of allocations.

**Comment by ktonga** [comment]
To see other places you can take a look at my WIP PR #5

**Comment by ktonga** [comment]
What is the difference (in terms of overhead) between `FromEA` and `Disjunction` trait? in both cases to invoke `absolve` you need to allocated an object to carry the two functions that take care of handling the disjunction, and with the trait it is a new instance of an anonymous class using inheritance which seems more verbose instead of just creating a value from a case class

**Comment by ktonga** [comment]
Ok, fair enough. But i think we cannot reuse instances due to the polymorphism on `E` and `A`

**Comment by jdegoes** [comment]
@ktonga Sure we can, we just need our good friend `asInstanceOf`. 😉

**Comment by ktonga** [comment]
Oh right. I forgot about that one.
